"""Plugin discovery and loading."""

from crows_nest.plugins.approval import (
    ApprovalHandler,
    ApprovalRequest,
    AutoApprovalHandler,
    QueuedApprovalHandler,
    check_cached_approval,
    configure_approval_handler,
    get_approval_handler,
    reset_approval_handler,
    user_approve,
)
from crows_nest.plugins.artifacts import (
    ApprovalDecision,
    ApprovalScope,
    LoadResult,
    LoadScope,
    OperationSpec,
    ParameterSpec,
    PluginArtifact,
    ResourceUsage,
    RiskLevel,
    Severity,
    TestResult,
    VerificationReport,
    Violation,
    ViolationType,
)
from crows_nest.plugins.generation import (
    configure_llm_provider,
    get_llm_provider,
    plugin_generate,
    reset_llm_provider,
)
from crows_nest.plugins.loader import (
    DEFAULT_PLUGIN_DIR,
    ENTRY_POINT_GROUP,
    PluginError,
    PluginInfo,
    PluginLoader,
    PluginLoadError,
    PluginNotFoundError,
    PluginSource,
    get_loaded_plugins,
    get_plugin_loader,
    load_plugins,
    reset_plugin_loader,
)
from crows_nest.plugins.loading import (
    load_artifact,
    plugin_load,
    unload_plugin,
)
from crows_nest.plugins.sandbox import (
    PluginVerifier,
    Sandbox,
    SandboxConfig,
    SandboxResult,
    StaticAnalyzer,
    TestCase,
)
from crows_nest.plugins.storage import (
    ArtifactStorage,
    get_artifact_storage,
    reset_artifact_storage,
)
from crows_nest.plugins.verification import (
    sandbox_verify,
    verify_artifact,
)

__all__ = [
    "DEFAULT_PLUGIN_DIR",
    "ENTRY_POINT_GROUP",
    "ApprovalDecision",
    "ApprovalHandler",
    "ApprovalRequest",
    "ApprovalScope",
    "ArtifactStorage",
    "AutoApprovalHandler",
    "LoadResult",
    "LoadScope",
    "OperationSpec",
    "ParameterSpec",
    "PluginArtifact",
    "PluginError",
    "PluginInfo",
    "PluginLoadError",
    "PluginLoader",
    "PluginNotFoundError",
    "PluginSource",
    "PluginVerifier",
    "QueuedApprovalHandler",
    "ResourceUsage",
    "RiskLevel",
    "Sandbox",
    "SandboxConfig",
    "SandboxResult",
    "Severity",
    "StaticAnalyzer",
    "TestCase",
    "TestResult",
    "VerificationReport",
    "Violation",
    "ViolationType",
    "check_cached_approval",
    "configure_approval_handler",
    "configure_llm_provider",
    "get_approval_handler",
    "get_artifact_storage",
    "get_llm_provider",
    "get_loaded_plugins",
    "get_plugin_loader",
    "load_artifact",
    "load_plugins",
    "plugin_generate",
    "plugin_load",
    "reset_approval_handler",
    "reset_artifact_storage",
    "reset_llm_provider",
    "reset_plugin_loader",
    "sandbox_verify",
    "unload_plugin",
    "user_approve",
    "verify_artifact",
]
